// swift-tools-version: 5.9.0
// AUTO-GENERATED by swift-binify - Prebuilt binary package
import PackageDescription

let package = Package(
    name: "Kingfisher",
    platforms: [.iOS(.v13), .macOS(.v10_15), .tvOS(.v13), .visionOS(.v1), .watchOS(.v6)],
    products: [
        .library(name: "Kingfisher", targets: ["Kingfisher"])
    ],
    targets: [
        .binaryTarget(
            name: "Kingfisher",
            url: "https://github.com/swift-bins/Kingfisher/releases/download/8.7.0/Kingfisher.xcframework.zip",
            checksum: "d274e74e004d0b4fbd98d968921f87ef1a8fd431a4ac79fc2df556e1f8d87e3d"
        )
    ]
)
