// swift-tools-version: 5.9.0
// AUTO-GENERATED by swift-binify - Prebuilt binary package
import PackageDescription

let package = Package(
    name: "Kingfisher",
    platforms: [.iOS(.v13), .macOS(.v10_15), .tvOS(.v13), .visionOS(.v1), .watchOS(.v6)],
    products: [
        .library(name: "Kingfisher", targets: ["Kingfisher"])
    ],
    targets: [
        .binaryTarget(
            name: "Kingfisher",
            url: "https://github.com/swift-bins/Kingfisher/releases/download/8.6.2/Kingfisher.xcframework.zip",
            checksum: "440ed551f9928640f24a59828a8fab19c290c3970d4052e1d45cb86777b6de62"
        )
    ]
)
